### PR TITLE
fix config + add embedded mode for inproc transport

### LINKED ISSUE #19: ignored config parameters
The following issues are related to this project and [rgb-node](https://github.com/LNP-BP/rgb-node).

1) in the ffi library, the function `start_rgb`, after collecting user's configuration in a `rgb::i9n::Config` struct

    e.g. `Config { stash_endpoint: Ipc("/tmp/rgb-node/testnet/stashd.rpc"), contract_endpoints: {Fungible: Ipc("/tmp/rgb-node/testnet/fungibled.rpc")}, network: Testnet3, threaded: true, data_dir: "/tmp/rgb-node/" }`

    it calls `rgb::i9n::Runtime::init(config)` which constructs `rgbd::Opts` using only some of the parameters of the configuration (`rgbd::Opts` contains: `verbose`, `bin_dir`, `data_dir`, `contracts` (list of contract names, without endpoints), `threaded`, `network`).

    This means that stash and contract endpoints are ignored. In fact they always get created in the default path (`{data_dir}/{network}/`). Do we want to provide the users with the possibility to set these endpoints or should we just remove them from the sdk?

2) calling `start_rgb` with `threaded: true` spawns a thread calling `rgbd::main_with_config` with the rgbd options. This call spawns two deamons: `stashd` and `fungibled`. But in doing that, it loses several configuration options, from [here](https://github.com/LNP-BP/rgb-node/blob/v0.2.0-beta.2/src/rgbd/runtime.rs#L62) you can see that only `data_dir` is retrieved from configuration. In fact `network` gets always set to the default value (`testnet`), both when calling it from the sdk and from the shell using the binary (in the latter case the only way to change the network is setting the `RGB_NETWORK` env variable)

3) to launch rgb in embedded mode we need to launch the daemons with specific `inproc` endpoints (which require `host[:port]` syntax, not a path). currently, with the bugs just described we cannot set them

----

I've reported these 3 problems together here (even if most of problems are related with rgb-node) because I think they need to be discussed together.

Moreover I'd like to understand why we need all of those `Config` and `Opts` structs:
```
$ git grep "struct Opts"
src/cli/config.rs:pub struct Opts {
src/contracts/fungible/config.rs:pub struct Opts {
src/rgbd/config.rs:pub struct Opts {
src/stash/config.rs:pub struct Opts {

$ git grep "struct Config"
src/cli/config.rs:pub struct Config {
src/contracts/fungible/config.rs:pub struct Config {
src/i9n/config.rs:pub struct Config {
src/rgbd/config.rs:pub struct Config {
src/stash/config.rs:pub struct Config {
```
some `Opts`/`Config` couples match, others don't, it's not clear to me. Is this duplication really necessary? From what I can see you're using config when launching a thread and opts when launching a new process. Am I correct?

### PR DESCRIPTION
**Pull request by zoedberg**
closes #19 

this is draft since we first need LNP-BP/rgb-node#110 to be merged and a tag to be added to rgb-node

fixes problem n.2 of #14

### CODE REVIEW

**Review by dr-orlovsky — APPROVED** [review]

**Comment by zoedberg** [comment]
For a recap of android issues, read [this](https://github.com/LNP-BP/rgb-sdk/issues/14#issuecomment-735677812).

I called the method `run_rgb_embedded` and for now left the other method as `start_rgb`, but I'm not totally convinced by the naming.

 `connect_rgb`, as a name of the other method, doesn't convince me because that entrypoint also allows to run rgb in an embedded mode (multi-threaded), by setting the `threaded` flag to `true`. So if anyone has some better naming ideas, welcome to report them here :)

**Comment by dr-orlovsky** [comment]
I think this PR is fine as is and can be merged now. Can you move it from the draft status?

As for the naming, the thing always runs RGB node and `threaded` parameter just makes it multithread, not multiprocess. So `connect_` will not work and the original name was ok.

**Comment by zoedberg** [comment]
> I think this PR is fine as is and can be merged now. Can you move it from the draft status?

I was waiting for a tag of rgb-node to use here. I've just seen you added one some hours ago, so now the PR is ready

> As for the naming, the thing always runs RGB node and threaded parameter just makes it multithread, not multiprocess. So connect_ will not work and the original name was ok.

I never talked about multiprocess and the way the threads are spawned is the same in both methods.
I'm trying to say that the only difference between the current `run_rgb_embedded` and `start_rgb` (with `threaded=true`) is the communication transport (one uses `inproc` and the other allows you to choose it, could be `inproc` also, in that case the two would have exactly the same behavior).

But, since I can't think of better names, we can just leave it as it is. We'll just need to add proper documentation to make the users understand the difference

**Review by dr-orlovsky — APPROVED** [review]

**Comment by dr-orlovsky** [comment]
So one functions is suitable for mobile environment and it always use multithreaded mode (not recommended for server or desktop). The other one allows configuration and not used for mobile. That's what I meant meaning we do not need threaded parameter in one and then the name makes sense. But not critical, so already merged.

**Comment by zoedberg** [comment]
> That's what I meant meaning we do not need threaded parameter in one and then the name makes sense. But not critical, so already merged.

Sorry but I can't find where you say that the `threaded` parameter can be removed (I'm assuming you intend from the `start_rgb` method). Could you point me out where you said this?

Moreover, I'm not sure it should be dropped, it's very useful, especially for demos

**Comment by dr-orlovsky** [comment]
No, what I am saying is that in embedded mode we do not need threaded parameter (and it's not there).

**Comment by zoedberg** [comment]
As you've just pointed out, `threaded` is not in the embedded mode method. So I'm not understanding what do you mean here:

> But not critical, so already merged.

**Pull request merged**
