### PR TITLE
Update rgb-node + add/fix sdk APIs

### LINKED ISSUE #28: Add `import_asset`, `export_asset`, `list_assets` and `invoice` methods
After closing LNP-BP/rgb-node#117, we should add the `import_asset` and `invoice` methods

### LINKED ISSUE #117: Expose `import_asset`, `export_asset` and `list_assets` methods
let's add to the `i9n` module the methods:
- `import_asset`, calling the method in `src/contracts/fungible/runtime.rs`
- ~~`invoice`, defined as here https://github.com/LNP-BP/rgb-node/blob/master/src/cli/fungible.rs#L412-L429~~ (https://github.com/LNP-BP/rgb-sdk/issues/28#issuecomment-739570302)
- `list_assets` (https://github.com/LNP-BP/rgb-sdk/issues/28#issuecomment-739324980)
- `export_asset`

@dr-orlovsky please correct me if I'm wrong

### PR DESCRIPTION
**Pull request by zoedberg**
this PR is in draft because:
- we need to close LNP-BP/rgb-node#117 first (and make a release so I can update rgb-node version)
- I'm not able to serialize the `ContractId` from `list_assets` in bech32, which is necessary since other APIs require the `asset_id` to be in bech32 format (maybe we just need to fix the format in which is saved? @dr-orlovsky if you please can look into this, I think it will take you way less time than me)

closes #28

### CODE REVIEW

**Comment by dr-orlovsky** [comment]
The reason with bech32 encoding is that it requires to use a `v0.2` release version of the LNP/BP and `v0.2.0-rc.3` of RGB Node, as I was explaining on the last dev call, where I had to re-implement hash types from rust-bitcoin in order to make it working with default `Display` and `FromStr` implementations.

Otherwise you need to use `to_bech32_str` method of the contract id when serializing to string

**Comment by zoedberg** [comment]
Ok, so I'll wait for rgb-node to update lnpbp to `v0.2.0`

**Comment by dr-orlovsky** [comment]
@zoedberg with https://github.com/LNP-BP/rgb-sdk/pull/31/commits/be0ebf42be91cd65a2da72656cd4edfbf8bf8686 this compiles against LNP/BP Core v0.2 release and RGB Node v0.2 RC5. Asset ids should be bech32 now, however I haven't tested that, pls let me know does this work.

**Comment by dr-orlovsky** [comment]
Waiting on @zoedberg to confirm that platform-specific libs are working with the rust library here and will merge it then

**Comment by zoedberg** [comment]
> with be0ebf4 this compiles against LNP/BP Core v0.2 release and RGB Node v0.2 RC5

I confirm, thanks for fixing it

> Asset ids should be bech32 now, however I haven't tested that, pls let me know does this work.

I've just checked that, unfortunately it seems that IDs are still in a hex format

**Comment by dr-orlovsky** [comment]
Ok, I will merge this and we will investigate `ContractId` as a separate issue/PR

**Comment by dr-orlovsky** [comment]
ContractId issue was closed by https://github.com/LNP-BP/rust-lnpbp/pull/168; just needs `cargo update` here

**Pull request merged**
