### PR TITLE
lost library issue fix 

### PR DESCRIPTION
**Pull request by alexeyneu**
fix for https://github.com/rgb-org/rgb-sdk/issues/51

### CODE REVIEW

**Comment by alexeyneu** [comment]
that what is in pr is just how i did it .

**Review by dr-orlovsky — CHANGES_REQUESTED** [review]
Sorry, this fixes nothing

**Comment by dr-orlovsky** [comment]
Screen Shot 2021-02-03 at 16 45 52

**Comment by alexeyneu** [comment]
i'll froce-push it later regardless of stuff you request. i've found real cause of all this stuff. that that `c++_shared` is absent in apk is not a real problem. So `rgb_node` should be `rgb` in  `System.loadLibrary()` ?  (see last post on issue)

**Pull request closed without merging**
