### PR TITLE
Android demo compile fixes

### PR DESCRIPTION
**Pull request by Jasonvdb**

### CODE REVIEW

**Comment by dr-orlovsky** [comment]
Thank you for fixing! That was strange the issue was not found out by the CI; will check once again why

**Comment by dr-orlovsky** [comment]
Thank you! That's strange that the build issue was not found by CI; will check why

**Review by dr-orlovsky — APPROVED** [review]

**Comment by Jasonvdb** [comment]
@dr-orlovsky this doesn't completely solve the issue though, it only gets the app to build. I still get this crash report mentioned at the bottom of this issue: https://github.com/LNP-BP/rgb-sdk/issues/47

**Comment by dr-orlovsky** [comment]
Yes, looking into that. Can I merge this PR? (I will do another one for the second half of the issue)

**Comment by Jasonvdb** [comment]
Thanks! Sure go for it.

**Pull request merged**
